export const AUTH_ACTION_TYPE = {
  AUTHORIZE_USER: "AUTHORIZE_USER",
  FETCH_AUTHORIZE_USER: "FETCH_AUTHORIZE_USER",
};

export const APP_ACTION_STATUS = {
  SUCCESS: "success",
  ERROR: "error",
  LOADING: "loading",
  INITIAL: "intial",
};
export const COMMON_ACTION_TYPES = {
  REQUEST: "_REQUEST",
  SUCCESS: "_SUCCESS",
  ERROR: "_ERROR",
  CLEAR: "_CLEAR",
  SET_ALERT_REQ: "_SET_ALERT_REQ",
  SET_ALERT: "_SET_ALERT",
  CLEAR_ALERT: "_CLEAR_ALERT",
};

export const ALERT_ACTION_TYPES = {
  TRIGGER_ALERT: "TRIGGER_ALERT",
};




export const STATIONS_ACTION_TYPE = {
  GET_ALL_STATIONS: "GET_ALL_STATIONS",
 
};
export const TRAIN_ACTION_TYPES  = {
  GET_ALL_TRAIN_LIST: "GET_ALL_TRAIN_LIST",
  ADD_TRAIN_DETAILS: "ADD_TRAIN_DETAILS",
  GET_TRAIN_DETAILS_BY_ID: "GET_TRAIN_DETAILS_BY_ID",
  EDIT_TRAIN_DETAILS:"EDIT_TRAIN_DETAILS",
  DELETE_TRAIN_DETAILS:"DELETE_TRAIN_DETAILS",
  GET_AVILIBLE_TRAINS:"GET_AVILIBLE_TRAINS",
  Get_TripDetails:"Get_TRIpDetails"
 
};
export const TICKET_ACTION_TYPES  = {
  GET_ALL_BOOKING_DETAILS: "GET_ALL_BOOKING_DETAILS",
  GET_BOOKING_DETAILS_BY_ID: "GET_BOOKING_DETAILS_BY_ID",
  CREATE_BOOKING: "CREATE_BOOKING",
  UPDATE_BOOKING: "UPDATE_BOOKING",
  CANCLE_BOOKING: "CANCLE_BOOKING",
};
export const TRAVELER_ACTION_TYPES  = {
  GET_ALL_TRAVELER_LIST: "GET_ALL_TRAVELER_LIST",
  ADD_TRAVELER: "ADD_TRAVELER",
  GET_TRAVELER_BY_ID: "GET_TRAVELER_BY_ID",
  UPDATE_TRAVELER_BY_ID: "UPDATE_TRAVELER_BY_ID",
  DELETE_TRAVELER_BY_ID: "DELETE_TRAVELER_BY_ID",
  LOGIN:"LOGIN",
  LOGIN_CLEAR:"LOGIN_CLEAR",
 
  

  
 
};